### ISSUE TITLE
JK Figure clarifications

### ISSUE THREAD

**Issue by kelle** [alejocosmico/NIRSpecFigures#33]
> o Figure 2 
> - What is the thick bar in this figure? The box is defined as the 25-75% percentile range and the "whiskers" (not a term I've ever seen used before for what look like error bars) are the 0-25% and 75-100% range. That are the thick red/black bars? They seem undefined.
> - Please show a representative 2MASS J-Ks uncertainty bar for a typical L dwarf
> somewhere on the plot.
> - How are quartiles defined for bins with 2,3,4,5,6 objects in them? surely they are 
> essentially meaningless, and you just have to show the mean and the full range spanned?

**Comment by alejocosmico** [comment]
I updated Figure 2 with the following:
* In the upper right I show the median J-K uncertainty of objects included in the templates.
* For samples with five or less objects, I just show the mean (circle) and min/max (whiskers). This means that we should update Tables 7 & 8 since some spectral types won't have quartiles. Use the quartiles_stats.txt file for that.

The caption for Figure 2 should now read:

"2MASS $J − K_s$ color versus spectral type for the L dwarfs in the optical-NIR sample included in the field templates (black symbols) and low gravity templates (red symbols). For each spectral type, whiskers cover the entire range and circles indicate the mean value. The number of objects used to calculate the statistics are indicated above the top whiskers. For samples with six or more objects, we indicate the interquartile range (i.e., second and third quartiles) with a box, and the median value with a horizontal line inside the box. The median $J − K_s$ uncertainty of all objects included in the templates is shown with a gray error bar in the upper right. Objects excluded from the templates are marked individually with crosses (field gravity: gray, low gravity: orange). The properties of the field and... "

**Comment by alejocosmico** [comment]
Also, the Note under Tables 7 & 8 should include:

"Only the mean, minimum, and maximum are shown for templates with five objects or less."

**Comment by kelle** [comment]
please add label to the J-K unc bar. Maybe it could go in the lower right corner (L8, 1.0). Also, just curious, what value did you use?

**Comment by kelle** [comment]
Why not list the median for bins with less than 5 objects? This still seems like a useful statistic to me. What do you think?

**Comment by alejocosmico** [comment]
OK I updated the location of the unc bar to the bottom right and added a label. Make sure you update the caption. The value I'm using is 0.05, which is the median unc of all objects included in the templates (field and low g). By contrast, the mean is 0.06, and the min/max are 0.03/0.18.

--------------------------------------------

The reviewer makes a fair point. In principle, the same way that quartiles lose meaning at such low sample sizes, so does the median. Even on samples with N<~25, the median has a greater probability of being significantly biased (i.e. of falling in a tail of the distribution). The best way to grasp the weakness of the median at such low sample is by thinking of its definition:

For odd numbered samples, the median is the central value; for even numbered samples, it's the average of the two central values. So, a sample size of e.g. N=3 could potentially have a big discrepancy between the median and the mean, with the former having much less information about the sample than the latter.

Having said that, the N=6 cutoff I'm making is rather arbitrary. I chose it so that we just lose the quartile stats only on the smallest field sample (L7). Here are the mean & median values for the samples with N<6:

L1   low-g :   N=5  mean=1.56  median=1.65
L2   low-g :       2              1.96                 1.96
L3   low-g :       3              1.89                 2.01
L4   low-g :       5              2.12                 2.02
L7   field :         4               2.02                2.07

The differences between mean and median are not horrendous, but they do tend to be larger than for the samples with N>=6. We could just include the median values for these samples in Tables 7 & 8 and let the reader decide whether to consider them meaningful.

All in all, I'm inclined to please the reviewer with this one (i.e. not publish 25th, median, 75th for these small samples). Plus, if we include these medians in Tables 7 & 8, that would send the message to the reader that *we* consider them meaningful, and I'm not so sure that we should.
